# Generated by Django 2.1.15 on 2022-10-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_auto_20221024_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='address',
            field=models.TextField(default='no address'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='gender',
            field=models.CharField(default='choose not to say', max_length=200),
        ),
        migrations.AddField(
            model_name='applicant',
            name='nationality',
            field=models.CharField(default='no country', max_length=200),
        ),
    ]
