# Generated by Django 2.1.15 on 2022-10-28 00:21

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('applicants', '0003_auto_20221027_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='Job_role',
            new_name='profession_Title',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='gender',
        ),
    ]
