# Generated by Django 2.1.15 on 2022-10-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0008_auto_20221028_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='profile_picture',
            field=models.ImageField(default='default-pp.JPG', upload_to=''),
        ),
    ]
