# Generated by Django 2.1.15 on 2022-10-28 02:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('applicants', '0005_auto_20221028_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skill_name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='skills1',
            field=models.ManyToManyField(blank=True, to='applicants.Skills'),
        ),
    ]
