# Generated by Django 2.1.15 on 2022-10-28 03:17

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('applicants', '0007_auto_20221028_0256'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='skills1',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='skill_name',
            new_name='name',
        ),
    ]
